spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 7 #警告阈值, 规则长度小于该值时会输出警告日志
    batch_size: 10000 #写入文件的批次大小
  rule:
    #远程规则
    remote:
      - name: 'anti-AD' #规则名称
        path: 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_21.txt' #规则地址
     
      - name: 'AdGuard DNS filter' #规则名称
        path: 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt' #规则地址
      
      - name: 'CHN: AdRules DNS List' #规则名称
        path: 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_29.txt' #规则地址
        
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - name: 'xndeye private List'
        path: 'private.txt'

  output:
    file_header: |  #输出文件头, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
      [xndeye Adblock List]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/xndeye/adblock_list
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
