spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 7 #警告阈值, 规则长度小于该值时会输出警告日志
    batch_size: 10000 #写入文件的批次大小
  rule:
    #远程规则
    remote:
      - name: 'anti-AD' #规则名称
        path: 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_21.txt' #规则地址
     
      - name: 'AdGuard DNS filter' #规则名称
        path: 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt' #规则地址
      
      - name: AdGuard 基础过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt

      - name: AdGuard 移动广告过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_11_Mobile/filter.txt

      - name: AdGuard 防跟踪保护过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt

      - name: AdGuard URL跟踪过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt

      - name: AdGuard 恼人广告过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt

      - name: AdGuard 解除搜索广告和自我推销过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_10_Useful/filter.txt

      - name: AdGuard 中文过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt

      - name: AdAway Default Blocklist
        path: https://adaway.org/hosts.txt

      - name: WindowsSpyBlocker
        path: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt

      - name: 大圣净化
        path: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts

      - name: AWAvenue-Adblock-Rule
        path: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Adblock-Rule/main/AWAvenue-Adblock-Rule.txt

      - name: halflife-list
        path: https://raw.githubusercontent.com/sbwml/halflife-list/master/ad-pc.txt

      - name: 1024_hosts
        path: https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts

      - name: AdBlocker Ultimate
        path: https://filters.adavoid.org/ultimate-ad-filter.txt

      - name: damengzhu/banad
        path: https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt

      - name: AWAvenue-Adblock-Rule
        path: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt

      - name: NoAppDownload
        path: https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt

      - name: xndeye web-ad-rule
        path: https://raw.githubusercontent.com/xndeye/web-ad-rule/master/easylist.txt

      - name: xinggsf movie
        path: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt

      - name: damengzhu jiekouAD
        path: https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt

      - name: cjxlist annoyance
        path: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt

      - name: ABP filters
        path: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt

      - name: ABP 反广告过滤
        path: https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt

      - name: uBlockOrigin privacy
        path: https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/privacy.txt

      - name: Telemetry Lists - Aggregated
        path: https://raw.githubusercontent.com/SystemJargon/filters/refs/heads/main/telemetry.txt

      - name: GoodbyeAds-Xiaomi
        path: https://cdn.jsdelivr.net/gh/jerryn70/GoodbyeAds@master/Extension/GoodbyeAds-Xiaomi-Extension.txt

      - name: GoodbyeAds-Huawei
        path: https://cdn.jsdelivr.net/gh/jerryn70/GoodbyeAds@master/Extension/GoodbyeAds-Huawei-AdBlock.txt

      - name: GoodbyeAds-Samsung
        path: https://cdn.jsdelivr.net/gh/jerryn70/GoodbyeAds@master/Extension/GoodbyeAds-Samsung-AdBlock.txt

      - name: GoodbyeAds
        path: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt

      - name: GoodbyeAds_YT
        path: https://cdn.jsdelivr.net/gh/jerryn70/GoodbyeAds@master/Extension/GoodbyeAds-YouTube-AdBlock.txt
        
    #本地规则
   # local: #本地规则请将文件移动到项目路径rule目录中
   #   - name: 'xndeye private List'
   #     path: 'private.txt'

  output:
    file_header: |  #输出文件头, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
      [xndeye Adblock List]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/xndeye/adblock_list
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
